// Generated by delombok at Thu Jan 08 10:39:56 GMT 2026
/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.gbif.occurrence.download.hive;

import org.gbif.dwc.terms.Term;
import javax.annotation.concurrent.Immutable;
import lombok.Generated;

/**
 * A field within the definition encapsulates the information linking the Hive field, the Term in the
 * enumeration and the type for the Hive table.
 */
@Immutable
@Generated
public class Field {
  private final String hiveField;
  private final String hiveDataType;
  private final Term term;

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof Field)) return false;
    final Field other = (Field) o;
    if (!other.canEqual((java.lang.Object) this)) return false;
    final java.lang.Object this$hiveField = this.getHiveField();
    final java.lang.Object other$hiveField = other.getHiveField();
    if (this$hiveField == null ? other$hiveField != null : !this$hiveField.equals(other$hiveField)) return false;
    final java.lang.Object this$hiveDataType = this.getHiveDataType();
    final java.lang.Object other$hiveDataType = other.getHiveDataType();
    if (this$hiveDataType == null ? other$hiveDataType != null : !this$hiveDataType.equals(other$hiveDataType)) return false;
    final java.lang.Object this$term = this.getTerm();
    final java.lang.Object other$term = other.getTerm();
    if (this$term == null ? other$term != null : !this$term.equals(other$term)) return false;
    return true;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  protected boolean canEqual(final java.lang.Object other) {
    return other instanceof Field;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final java.lang.Object $hiveField = this.getHiveField();
    result = result * PRIME + ($hiveField == null ? 43 : $hiveField.hashCode());
    final java.lang.Object $hiveDataType = this.getHiveDataType();
    result = result * PRIME + ($hiveDataType == null ? 43 : $hiveDataType.hashCode());
    final java.lang.Object $term = this.getTerm();
    result = result * PRIME + ($term == null ? 43 : $term.hashCode());
    return result;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public Field(final String hiveField, final String hiveDataType, final Term term) {
    this.hiveField = hiveField;
    this.hiveDataType = hiveDataType;
    this.term = term;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public String getHiveField() {
    return this.hiveField;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public String getHiveDataType() {
    return this.hiveDataType;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public Term getTerm() {
    return this.term;
  }
}
