// Generated by delombok at Thu Jan 08 10:39:56 GMT 2026
/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.gbif.occurrence.download.hive;

import org.gbif.dwc.terms.Term;
import javax.annotation.concurrent.Immutable;
import static org.gbif.occurrence.download.hive.HiveColumns.escapeColumnName;

/**
 * A field encapsulates the information linking the Hive field to the Term in the enumeration, the type for the Hive table
 * and a SQL fragment that can be used to initialize the field.  This is useful for create tables as follows:
 * <code>CREATE TABLE t2(id INT)</code>
 * <code>INSERT OVERWRITE TABLE t2 SELECT customUDF(x) FROM t1</code>
 * In the above example, the customUDF(x) is part of the field definition.
 */
@Immutable
public class InitializableField {
  private final String initializer;
  private final String columnName;
  private final String hiveField;
  private final String hiveDataType;
  private final Term term;

  /**
   * Default behavior is to initialize with the same as the Hive table column, implying the column is a straight copy
   * with the same name as an existing table.
   */
  public InitializableField(Term term, String columnName, String hiveDataType) {
    this.term = term;
    this.columnName = columnName;
    this.hiveField = escapeColumnName(columnName);
    this.hiveDataType = hiveDataType;
    initializer = hiveField;
  }

  public InitializableField(Term term, String columnName, String hiveDataType, String initializer) {
    this.term = term;
    this.columnName = columnName;
    this.hiveField = escapeColumnName(columnName);
    this.hiveDataType = hiveDataType;
    this.initializer = initializer == null ? hiveField : initializer; // for safety
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public String getInitializer() {
    return this.initializer;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public String getColumnName() {
    return this.columnName;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public String getHiveField() {
    return this.hiveField;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public String getHiveDataType() {
    return this.hiveDataType;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public Term getTerm() {
    return this.term;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof InitializableField)) return false;
    final InitializableField other = (InitializableField) o;
    if (!other.canEqual((java.lang.Object) this)) return false;
    final java.lang.Object this$initializer = this.getInitializer();
    final java.lang.Object other$initializer = other.getInitializer();
    if (this$initializer == null ? other$initializer != null : !this$initializer.equals(other$initializer)) return false;
    final java.lang.Object this$columnName = this.getColumnName();
    final java.lang.Object other$columnName = other.getColumnName();
    if (this$columnName == null ? other$columnName != null : !this$columnName.equals(other$columnName)) return false;
    final java.lang.Object this$hiveField = this.getHiveField();
    final java.lang.Object other$hiveField = other.getHiveField();
    if (this$hiveField == null ? other$hiveField != null : !this$hiveField.equals(other$hiveField)) return false;
    final java.lang.Object this$hiveDataType = this.getHiveDataType();
    final java.lang.Object other$hiveDataType = other.getHiveDataType();
    if (this$hiveDataType == null ? other$hiveDataType != null : !this$hiveDataType.equals(other$hiveDataType)) return false;
    final java.lang.Object this$term = this.getTerm();
    final java.lang.Object other$term = other.getTerm();
    if (this$term == null ? other$term != null : !this$term.equals(other$term)) return false;
    return true;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  protected boolean canEqual(final java.lang.Object other) {
    return other instanceof InitializableField;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final java.lang.Object $initializer = this.getInitializer();
    result = result * PRIME + ($initializer == null ? 43 : $initializer.hashCode());
    final java.lang.Object $columnName = this.getColumnName();
    result = result * PRIME + ($columnName == null ? 43 : $columnName.hashCode());
    final java.lang.Object $hiveField = this.getHiveField();
    result = result * PRIME + ($hiveField == null ? 43 : $hiveField.hashCode());
    final java.lang.Object $hiveDataType = this.getHiveDataType();
    result = result * PRIME + ($hiveDataType == null ? 43 : $hiveDataType.hashCode());
    final java.lang.Object $term = this.getTerm();
    result = result * PRIME + ($term == null ? 43 : $term.hashCode());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public java.lang.String toString() {
    return "InitializableField(initializer=" + this.getInitializer() + ", columnName=" + this.getColumnName() + ", hiveField=" + this.getHiveField() + ", hiveDataType=" + this.getHiveDataType() + ", term=" + this.getTerm() + ")";
  }
}
